# This is a configuration file for the bacon tool
# Bacon repository: https://github.com/Canop/bacon
# Complete help on configuration: https://dystroy.org/bacon/config/
# You can also check bacon's own bacon.toml file
#  as an example: https://github.com/Canop/bacon/blob/main/bacon.toml

default_job = "run"

[jobs.run]
command = ["cargo", "run"]
need_stdout = true
watch = ["src", "templates", "Cargo.toml"]